## Soluciones 

### Solución 1

In [1]:
A <- matrix(rep(seq(1, 5), 5), nrow=5)+matrix(rep(seq(0, 4), 5), byrow=TRUE, nrow=5)
A

[,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4    5   
[2,] 2    3    4    5    6   
[3,] 3    4    5    6    7   
[4,] 4    5    6    7    8   
[5,] 5    6    7    8    9

In [2]:
# Funcion de Hankel

Hankel <- function(x){
    A <- matrix(rep(seq(1, x), x), nrow=x)+matrix(rep(seq(0, x-1), x), byrow=TRUE, nrow=x)
    return(A)
    }

In [3]:
Hankel(10)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,]  1    2    3    4    5    6    7    8    9   10   
 [2,]  2    3    4    5    6    7    8    9   10   11   
 [3,]  3    4    5    6    7    8    9   10   11   12   
 [4,]  4    5    6    7    8    9   10   11   12   13   
 [5,]  5    6    7    8    9   10   11   12   13   14   
 [6,]  6    7    8    9   10   11   12   13   14   15   
 [7,]  7    8    9   10   11   12   13   14   15   16   
 [8,]  8    9   10   11   12   13   14   15   16   17   
 [9,]  9   10   11   12   13   14   15   16   17   18   
[10,] 10   11   12   13   14   15   16   17   18   19

In [4]:
Hankel(12)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12]
 [1,]  1    2    3    4    5    6    7    8    9   10    11    12   
 [2,]  2    3    4    5    6    7    8    9   10   11    12    13   
 [3,]  3    4    5    6    7    8    9   10   11   12    13    14   
 [4,]  4    5    6    7    8    9   10   11   12   13    14    15   
 [5,]  5    6    7    8    9   10   11   12   13   14    15    16   
 [6,]  6    7    8    9   10   11   12   13   14   15    16    17   
 [7,]  7    8    9   10   11   12   13   14   15   16    17    18   
 [8,]  8    9   10   11   12   13   14   15   16   17    18    19   
 [9,]  9   10   11   12   13   14   15   16   17   18    19    20   
[10,] 10   11   12   13   14   15   16   17   18   19    20    21   
[11,] 11   12   13   14   15   16   17   18   19   20    21    22   
[12,] 12   13   14   15   16   17   18   19   20   21    22    23

### Solución 2

* Una función se **vectoriza** si el resultado de aplicar esto  a un vector es idéntico al resultado de aplicar la función a los elementos separados y combinar los valores resultantes en un vector.

* Una función de varios argumentos obedece a la regla de **reciclaje** si el resultado de aplicar la función a vectores de diferentes longitudes,  se recicla a la longitud del vector más grande  y luego la función se aplica a los elementos correspondientes de los argumentos y finalmente los resultados se juntan en un vector.

Si consideramos la función matemática definida por:

$$h(x,y) = \sqrt{x^2 + y^2}$$

podemos considerar escribir una función llamada `hipot` con argumentos `x` e `y` que implementa una versión vectorizada que obedece la regla de reciclaje.

In [5]:
hipot <- function(x, y) sqrt(x^2 + y^2)

### Solución 3

In [6]:
# Solucion(a)

# Las versiones mas simple de las funciones son

primero <- function(x, cantidad =1)
    x[1: cantidad]
    
ultimo <- function(x, cantidad = 1)
    x[length(x) + 1 - cantidad:1]

In [7]:
### Solucion(b)

# Versiones mas complejas del problema

primero <- function(x, cantidad= 1)
    x[1:min(length(x), cantidad)]

ultimo <- function(x, cantidad = 1)
    x[length(x) + 1 - min(length(x), cantidad):1]

In [8]:
### Solucion(c)

primero <- function(x, cantidad = 1)
    x[1:cantidad]
    
ultimo <- function(x, cantidad = 1)
    c(rep(NA, max(cantidad - length(x), 0)), 
      x[length(x) + 1 - min(length(x), cantidad): 1])

### Solución 4

In [9]:
set.seed(75)
aMat <- matrix( sample(10, size=60, replace=T), nr=6)

# Solucion(a)

apply(aMat, 1, function(x){sum(x>4)})

[1] 4 7 6 2 6 7

In [10]:
# Solucion(b)

which( apply(aMat,1,function(x){sum(x==7)==2}) )

[1] 5

In [11]:
# Solucion(c)

aMatColSums <- colSums(aMat)
cbind( rep(1:10,rep(10,10)), rep(1:10,10) ) [outer(aMatColSums,aMatColSums,"+")>75,]

[,1] [,2]
[1,] 2    2   
[2,] 2    6   
[3,] 2    8   
[4,] 6    2   
[5,] 6    8   
[6,] 8    2   
[7,] 8    6   
[8,] 8    8

### Solución 5

In [12]:
Q <-  function(theta) sum(abs(y - theta[1] - theta[2] * x))

`optim` toma una primera aproximación inicial para `a` y `b` (por ejemplo, los obtenidos por mínimos cuadrados) y la función `Q` como argumentos y busca los valores que minimizan `Q`.

```
theta = lsfit(x, y)$coef
z = optim(theta, Q)
```

In [13]:
help(optim)