###  Aplicaciones y ejemplos de vectores y matrices


Ejemplo de la matriz de covarianza, dado por [Norman Matloff](http://heather.cs.ucdavis.edu/matloff.html) y del fantástico [Art of R Programming: A Tour of Statistical Software Design](https://www.nostarch.com/artofr.htm).

In [2]:
# Usando las funciones row() y col() cuyos argumentos son matrices

matrizcoV <- function(rho,n) {
    m <- matrix(nrow=n,ncol=n)
    m <- ifelse(row(m) == col(m),1,rho) 
    return(m)
}
matrizcoV(0.2,3)

[,1] [,2] [,3]
[1,] 1.0  0.2  0.2 
[2,] 0.2  1.0  0.2 
[3,] 0.2  0.2  1.0

Una práctica común en R es el de  visualizar la dimensionalidad de los datos. Los datos siguientes representan las cifras iniciales en la verificación de una oficial de reembolso de seguro, cuando un auditor financiero, le pidió investigar por fraude.



In [3]:
accdato <- c(1, 132, 86.7,
            2, 50, 50.7,
            3, 32, 36.0,
            4, 20, 27.9,
            5, 19, 22.8,
            6, 11, 19.3,
            7, 10, 16.7,
            8, 9, 14.7,
            9, 5, 13.2)
accdato

[1]   1.0 132.0  86.7   2.0  50.0  50.7   3.0  32.0  36.0   4.0  20.0  27.9
[13]   5.0  19.0  22.8   6.0  11.0  19.3   7.0  10.0  16.7   8.0   9.0  14.7
[25]   9.0   5.0  13.2

Acomodamos mejor el vector, como una matriz `9x3`  cuyas columnas se llaman `numero`, `actual`, `v_esperado`:

In [4]:
accdato <- matrix(accdato, 9, 3, byrow = TRUE)
colnames(accdato) <- c("numero", "actual", "v_esperado")
accdato

numero actual v_esperado
 [1,] 1      132    86.7      
 [2,] 2       50    50.7      
 [3,] 3       32    36.0      
 [4,] 4       20    27.9      
 [5,] 5       19    22.8      
 [6,] 6       11    19.3      
 [7,] 7       10    16.7      
 [8,] 8        9    14.7      
 [9,] 9        5    13.2

Podemos ahora usar el test de *chi-cuadrado* para averiguar si es que ha habido un fraude, a través de la desviación significativa o no de los datos reales y de los esperados. Escribamos el test para estos datos:

In [5]:
chi2 <-sum((accdato[,2] -accdato[,3])^2/accdato[,3])
chi2

[1] 40.55482

¿ Habrá habido fraude...?

El poder de las matrices en R, ocurre cuando realizamos operaciones (multiplicación, inversión, transposición, etc) comunes de  matrices y sus respectivas restricciones:


In [6]:
A <- matrix(c(6,2,3, 4,
             0, -8,2, 1,
             8, -3, 7, -5),3, 4, byrow = TRUE)
B <- matrix(c(-7,12,3, 9,
             6, 2, 0, -1,
             11, 5, -12, 8),3, 4, byrow = TRUE)
A+B
A-B

[,1] [,2] [,3] [,4]
[1,] -1   14    6   13  
[2,]  6   -6    2    0  
[3,] 19    2   -5    3

[,1] [,2] [,3] [,4]
[1,] 13   -10   0    -5 
[2,] -6   -10   2     2 
[3,] -3    -8  19   -13

In [7]:
A * B   # Multiplicacion componente a componente

[,1] [,2] [,3] [,4]
[1,] -42   24    9   36 
[2,]   0  -16    0   -1 
[3,]  88  -15  -84  -40

In [8]:
A %*% B  # Multiplicacion usual de matrices

ERROR: Error in A %*% B: argumentos no compatibles


El cálculo de la inversa de una matriz se realiza de la siguiente manera:

In [10]:
A <- matrix(c(4, 10, 6, 1 , 13, 5,
           4,5, -2, 1, 8, 4,
             -7, 5, 2, 1, 3, -4,
             2,3, 4 ,5 , 6, 7,
             1,3, 5,6, 7,-3,
             0, 9, 7, 1,3, 4), 6, 6, byrow=TRUE)
B <- solve(A)   ## Calculamos  la inversa de A
B

[,1]         [,2]        [,3]          [,4]        [,5]        
[1,] -0.025081101  0.06307221 -0.1373002523 -0.10063679  0.088207377
[2,] -0.116454403  0.15776162  0.0044154752 -0.08475309  0.035185630
[3,]  0.114051424 -0.18525171 -0.0355340622  0.01403340  0.007995915
[4,] -0.182416196  0.12315872  0.0002102607  0.06399135  0.110519044
[5,]  0.132193920 -0.05770155  0.0494112700  0.03796708 -0.028024751
[6,]  0.008891025 -0.01828668  0.0151387721  0.12166286 -0.099771717
     [,6]       
[1,]  0.07324883
[2,]  0.16692899
[3,] -0.01140815
[4,]  0.07597621
[5,] -0.14559053
[6,] -0.01542713

In [11]:
A %*% B

[,1]          [,2]          [,3]          [,4]          [,5]        
[1,]  1.000000e+00 -6.938894e-16 -1.249001e-16  1.110223e-16 0.000000e+00
[2,] -1.734723e-16  1.000000e+00 -5.551115e-17  0.000000e+00 1.110223e-16
[3,] -4.857226e-17 -1.387779e-17  1.000000e+00  0.000000e+00 0.000000e+00
[4,] -1.387779e-16 -1.110223e-16  1.387779e-17  1.000000e+00 0.000000e+00
[5,]  2.983724e-16 -2.220446e-16 -1.387779e-17 -5.551115e-17 1.000000e+00
[6,] -6.938894e-18 -2.081668e-16  5.551115e-17  0.000000e+00 0.000000e+00
     [,6]         
[1,] -8.326673e-17
[2,]  2.428613e-16
[3,] -7.632783e-17
[4,] -1.804112e-16
[5,] -1.249001e-16
[6,]  1.000000e+00

In [12]:
B %*% A

[,1]          [,2]          [,3]          [,4]          [,5]         
[1,]  1.000000e+00  0.000000e+00  4.440892e-16 -9.714451e-17 -1.665335e-16
[2,] -2.567391e-16  1.000000e+00  2.220446e-16  2.775558e-17 -3.330669e-16
[3,]  1.908196e-16  0.000000e+00  1.000000e+00 -3.469447e-18  2.706169e-16
[4,] -1.110223e-16 -2.220446e-16 -2.220446e-16  1.000000e+00 -3.330669e-16
[5,]  2.428613e-17 -2.220446e-16  0.000000e+00  0.000000e+00  1.000000e+00
[6,]  0.000000e+00 -1.110223e-16 -1.249001e-16  5.204170e-18  1.387779e-17
     [,6]         
[1,]  5.551115e-17
[2,] -1.110223e-16
[3,]  1.595946e-16
[4,] -2.220446e-16
[5,]  0.000000e+00
[6,]  1.000000e+00

Para ejemplos de orden menor, se cumple que *AB= I = BA*

In [13]:
M <- matrix(c(4,0,5,
             0,1, -6,
             3,0,4),3,3, byrow=TRUE)
N <- solve(M)
N

[,1] [,2] [,3]
[1,]   4  0    -5  
[2,] -18  1    24  
[3,]  -3  0     4

In [14]:
N%*%M

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    1    0   
[3,] 0    0    1

In [15]:
M %*%N

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    1    0   
[3,] 0    0    1

Uno de los aspectos más importantes de **R** es la familia de funciones `apply()` tales como `apply()`, `tapply()` y `lapply()`. La funci?n `apply()` instruye a R a llamar una función  sobre cada fila o columna de una matriz. Esta es la forma general de `apply()` para matrices 

```
apply(m, dimcode, f, fargs)
```

donde los  argumentos son como sigue:

* ` m` es una matriz.
*  `dimcode` es la dimensión, igual a 1, si la función aplica a filas o 2 si la función aplica a columnas.
*  `f` es la función a ser aplicada.
*  `fargs` es un conjunto opcional de argumentos dados a `f`.

In [16]:
# help(apply): Fuertemente leer las notas
# example(apply)

dw<- matrix(c(1,2,3,4,5,6), nrow=3)
dw
apply(dw, 1, mean)

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

[1] 2.5 3.5 4.5

Un ejemplo utilizando una función escrita por el usuario:

In [17]:
dw
f <-function(x)x/c(2,5)
dw1<- apply(dw, 1, f)
dw1

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

[,1] [,2] [,3]
[1,] 0.5  1    1.5 
[2,] 0.8  1    1.2

In [18]:
t(apply(dw,1,f))

[,1] [,2]
[1,] 0.5  0.8 
[2,] 1.0  1.0 
[3,] 1.5  1.2

Un ejemplo más avanzado desde Norman Matloff, (The Art of R Programming):

In [19]:
matriz0 <-function(fila,d) {
    maj <- sum(fila[1:d]) / d
    return(if(maj > 0.5) 1 else 0)
}
ax <-matrix(c(1,1,1,0, 0,1,0,1, 1, 1, 0,1, 1,1,1,1, 0,0,0,0), nrow=4)
ax
apply(ax,1,matriz0,3)
apply(ax,1,matriz0,2)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    0    1    1    0   
[2,] 1    1    1    1    0   
[3,] 1    0    0    1    0   
[4,] 0    1    1    1    0

[1] 1 1 0 1

[1] 0 1 0 0

El uso de `apply()` no acelera el código. El beneficio de utilizar esta función es que hace el código mucho más  compacto y por tanto más fácil de leer y modificar  evitando  posibles errores en la escritura de código cuando se trabaja con bucles.

Por otra parte, cuando R  desarrolla el procesamiento en paralelo, funciones como `apply()` serán muy útiles e importantes. Por ejemplo, la función `clusterApply()` en el paquete `snow` de R da cierta capacidad de procesado en paralelo mediante la distribución de los datos de una submatriz a varios nodos de una red.


La función `outer` aplica una función a dos arrays, en realidad esta función devuelve el producto exterior de dos vectores o puedes pasar una función como tercer paramétro. 

In [20]:
outer(1:6, 1:6, paste)

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1 1  1 2  1 3  1 4  1 5  1 6 
[2,] 2 1  2 2  2 3  2 4  2 5  2 6 
[3,] 3 1  3 2  3 3  3 4  3 5  3 6 
[4,] 4 1  4 2  4 3  4 4  4 5  4 6 
[5,] 5 1  5 2  5 3  5 4  5 5  5 6 
[6,] 6 1  6 2  6 3  6 4  6 5  6 6

In [21]:
x<- c(1,2.3,2,3,4,8,12,43)
y<- c(2,4)
outer(x,y,"log")

[,1]     [,2]     
[1,] 0.000000 0.0000000
[2,] 1.201634 0.6008169
[3,] 1.000000 0.5000000
[4,] 1.584963 0.7924813
[5,] 2.000000 1.0000000
[6,] 3.000000 1.5000000
[7,] 3.584963 1.7924813
[8,] 5.426265 2.7131324

In [22]:
(valores <- outer(1:5, 1:5, FUN = "paste", sep = ","))
valores[c(4, 15)]

[,1] [,2] [,3] [,4] [,5]
[1,] 1,1  1,2  1,3  1,4  1,5 
[2,] 2,1  2,2  2,3  2,4  2,5 
[3,] 3,1  3,2  3,3  3,4  3,5 
[4,] 4,1  4,2  4,3  4,4  4,5 
[5,] 5,1  5,2  5,3  5,4  5,5

[1] "4,1" "5,3"

####  El método del Simplex 
 
Sea el problema de programación lineal, que será resuelto por el [simplex algorithm](https://jeremykun.com/2014/12/01/linear-programming-and-the-simplex-algorithm/)


min C = 5x<sub>1</sub> + 8x<sub>2</sub>

sujeto a los restricciones

x<sub>1</sub> + x<sub>2</sub> >=2

x<sub>1</sub> + 2x<sub>2</sub> >=3 

y

x<sub>1</sub>, x<sub>2</sub> >= 0

Para resolver este problema usamos los paquetes  [lpSolve-lpSolveApi](http://lpsolve.r-forge.r-project.org/) de la siguiente manera :

```
install.packages("lpSolve")
install.packages("lpSolveAPI")
```


In [25]:
library(lpSolve)
ejemplo.pl <- lp(objective.in=c(5, 8), const.mat=matrix(c(1, 1, 1, 2),nrow=2), const.rhs=c(2, 3), const.dir=c(">=", ">="))
ejemplo.pl
ejemplo.pl$solution

Success: the objective function is 13 

[1] 1 1

La salida nos dice que el valor que minimiza el problema, está en x<sub>1</sub> = 1, x<sub>2</sub> = 1
y el mínimo valor de la función objetivo es 13.


#### Descomposición de Cholesly

La factorización de Cholesly es un método de descomposición de una matriz definida positiva. Algunas [aplicaciones de la descomposicion de Cholesky](https://en.wikipedia.org/wiki/Cholesky_decomposition#Applications) incluye las soluciones de ecuaciones lineales, simulación de Montecarlo y los filtros de Kalman.

La función `chol()` lleva a cabo la descomposición de una matriz definida positiva. 


In [26]:
A = as.matrix(data.frame(c(3,4,3),c(4,8,6),c(3,6,9)))
colnames(A) <- NULL
A

[,1] [,2] [,3]
[1,] 3    4    3   
[2,] 4    8    6   
[3,] 3    6    9

Factorizamos la matriz con la función `chol()`:


In [29]:
A.chol <- chol(A)
A.chol

[,1]     [,2]     [,3]    
[1,] 1.732051 2.309401 1.732051
[2,] 0.000000 1.632993 1.224745
[3,] 0.000000 0.000000 2.121320

La función `chol()` devuelve una matriz triangular superior. La transposición de la matriz  produce una matriz triangular inferior:

In [30]:
t(A.chol)

[,1]     [,2]     [,3]   
[1,] 1.732051 0.000000 0.00000
[2,] 2.309401 1.632993 0.00000
[3,] 1.732051 1.224745 2.12132

y esto coincide con el resultado de la salida de la funci?n `chol()`.  Podemos verificar el resultado:

In [31]:
t(A.chol) %*% A.chol

[,1] [,2] [,3]
[1,] 3    4    3   
[2,] 4    8    6   
[3,] 3    6    9

Lectura : [Algorithm for Cholesky decomposition](http://www.math.sjsu.edu/~foster/m143m/cholesky.pdf).